# manifest kubernetes file
apiVersion: apps/v1

kind: Deployment

metadata:
  name: fact-deployment

  labels:
    app: factorial

spec:
  replicas: {{ .Values.deployment.replicas }}

  selector:
    matchLabels:
      app: factorial

  template:
    metadata:
      # annotations:
      #   prometheus.io/port: "3500"
      #   prometheus.io/path: "/metrics"
      #   prometheus.io/scrape: "true"
      labels:
        app: factorial

    spec:
      containers:
        - name: factorial

          image: docker.io/laykidi/factorial:{{ .Values.image.tag }}

          ports:
            - containerPort: 3500
          env:
           # The first env  variable gets the host ip (the node ip). 
           # this env variable is not static, it's known in the run time.
            - name: HOST_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
           # the second env variable uses the previous variable.
            - name: OTEL_EXPORTER_OTLP_ENDPOINT  
              value: "http://$(HOST_IP):55680"
            - name: OTEL_SERVICE_NAME
              value: "fact-service"
