apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Hazem-Atya/oberservability.git'
    path: 05-agrocd-gitops/chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fact-service
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true